version: "3.7"

services:

  reverseproxy:
    build:
      context: ./Nginx
      dockerfile: Nginx.Dockerfile
    ports:
      - "81:80"
    environment:
      - hostname=localhost
      - API_HOST=api
    restart: always

  api:
    depends_on:
      - reverseproxy
    build:
      context: ./Api
      dockerfile: Api.Dockerfile
    expose:
      - "5000"
    restart: always